In [1]:
import pandas as pd
import numpy as np

### Q1. Above data is data for prebid auctions. There are bidders who receive requests for placing ads, they respond to these requests with a bid and the highest bid wins the auction. Analyze the dataset to answer which bidder has the highest win rate (wins / total_bid)?

In [2]:
df = pd.read_csv('analysis.csv')
df.head()

,Unnamed: 0,date_hour,client,device_type,time_zone,os_name,browser_name,ad_unit,size,bidder,...,sum_time_to_respond,median,min_bid,max_bid,avg_bid,sum_2nd_highest_bid,sum_prebid_winning_bid,sum_winning_bid,sum_nobid,sum_timeout
0,0,2021-04-11T01:00:00,asc126828,Desktop,America/Chicago,Linux,Chrome-85.04183133,div-gpt-ad-BT-D-Footers,728x90,onemobile,...,6614.0,NaN,0.58520,0.58520,0.585200,0.5852,0.5852,NaN,NaN,NaN
1,1,2021-04-11T01:00:00,asc126828,Desktop,America/Chicago,Linux,Chrome-85.04183133,div-gpt-ad-BT-D-Footers,728x90,rhythmone,...,5171.0,NaN,0.33945,0.34875,0.344100,NaN,NaN,NaN,NaN,NaN
2,2,2021-04-11T01:00:00,asc126828,Desktop,America/Chicago,Linux,Chrome-85.04183133,div-gpt-ad-BT-D-InLine-1,300x250,undertone,...,1523.0,NaN,0.96000,0.96000,0.960000,NaN,NaN,NaN,NaN,NaN
3,3,2021-04-11T01:00:00,asc126828,Desktop,America/Chicago,Linux,Chrome-85.04183133,div-gpt-ad-BT-D-O-300x250-1,300x250,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,2021-04-11T01:00:00,asc126828,Desktop,America/Chicago,Linux,Chrome-85.04183133,div-gpt-ad-BT-D-O-300x250-1,300x250,rhythmone,...,3570.0,0.34875,0.34410,0.34875,0.346425,NaN,NaN,NaN,NaN,NaN

In [3]:
df.columns

Index(['Unnamed: 0', 'date_hour', 'client', 'device_type', 'time_zone',
       'os_name', 'browser_name', 'ad_unit', 'size', 'bidder', 'bid_range',
       'media_type', 'request_count', 'response_count', 'prebid_win_count',
       'win_count', 'sum_bid', 'sum_time_to_respond', 'median', 'min_bid',
       'max_bid', 'avg_bid', 'sum_2nd_highest_bid', 'sum_prebid_winning_bid',
       'sum_winning_bid', 'sum_nobid', 'sum_timeout'],
      dtype='object')

In [4]:

bidder_data = df.groupby('bidder', axis = 0).sum()

/var/folders/gm/d4dyg8m94cg5y5x1zr8sjhy40000gn/T/ipykernel_29151/2004450753.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  bidder_data = df.groupby('bidder', axis = 0).sum()

In [5]:
bidder_data = bidder_data[['prebid_win_count', 'win_count']]
bidder_data.columns

Index(['prebid_win_count', 'win_count'], dtype='object')

In [6]:
bid_count = df.groupby('bidder').count()
bid_count

,Unnamed: 0,date_hour,client,device_type,time_zone,os_name,browser_name,ad_unit,size,bid_range,...,sum_time_to_respond,median,min_bid,max_bid,avg_bid,sum_2nd_highest_bid,sum_prebid_winning_bid,sum_winning_bid,sum_nobid,sum_timeout
bidder,,,,,,,,,,,,,,,,,,,,,
,1210,1210,1210,1210,1210,1210,1210,1210,1210,1210,...,0,0,0,0,0,0,0,0,0,0
33across,240,240,240,240,240,240,240,240,240,240,...,240,113,240,240,240,54,74,13,0,0
appnexus,197,197,197,197,197,197,197,197,197,197,...,197,102,197,197,197,42,71,9,0,0
criteo,306,306,306,306,306,306,306,306,306,306,...,306,103,306,306,306,45,100,14,0,0
emx_digital,169,169,169,169,169,169,169,169,169,169,...,169,108,169,169,169,37,43,13,0,0
ix,464,464,464,464,464,464,464,464,464,464,...,464,196,464,464,464,81,102,11,0,0
medianet,384,384,384,384,384,384,384,384,384,384,...,384,135,384,384,384,59,108,16,0,0
onemobile,407,407,407,407,407,407,407,407,407,407,...,407,175,407,407,407,72,188,31,0,0
openx,197,197,197,197,197,197,197,197,197,197,...,197,103,197,197,197,39,42,7,0,0
pubmatic,298,298,298,298,298,298,298,298,298,298,...,298,137,298,298,298,55,82,19,0,0
pulsepoint,134,134,134,134,134,134,134,134,134,134,...,134,102,134,134,134,44,59,5,0,0
rhythmone,246,246,246,246,246,246,246,246,246,246,...,246,123,246,246,246,61,87,13,0,0
rubicon,178,178,178,178,178,178,178,178,178,178,...,178,89,178,178,178,35,26,0,0,0
sharethrough,139,139,139,139,139,139,139,139,139,139,...,139,70,139,139,139,28,64,9,0,0
sovrn,102,102,102,102,102,102,102,102,102,102,...,102,60,102,102,102,28,10,1,0,0
teads,48,48,48,48,48,48,48,48,48,48,...,48,8,48,48,48,7,28,7,0,0
triplelift,232,232,232,232,232,232,232,232,232,232,...,232,106,232,232,232,41,54,6,0,0
undertone,49,49,49,49,49,49,49,49,49,49,...,49,30,49,49,49,6,29,12,0,0

In [7]:
# bid_count.drop(['prebid_win_count', 'win_count'], axis=1)
bid_count_1 = bid_count['date_hour']
bid_count_1 
bidder_data_1 = bidder_data.join(bid_count_1)

In [8]:
bidder_data_1['win_rate'] = bidder_data_1['win_count']/bidder_data_1['date_hour']
bidder_data_1
# print(bidder_data_1['win_rate'].max())
bidder_data_1['win_rate'].sort_values(ascending=False)

bidder
teads           0.333333
undertone       0.326531
pubmatic        0.191275
emx_digital     0.118343
onemobile       0.085995
33across        0.079167
rhythmone       0.073171
sharethrough    0.071942
criteo          0.068627
medianet        0.052083
appnexus        0.050761
triplelift      0.043103
pulsepoint      0.037313
openx           0.035533
ix              0.028017
sovrn           0.009804
rubicon         0.000000
                0.000000
Name: win_rate, dtype: float64

In [9]:
bidder_data_1

              prebid_win_count  win_count  date_hour  win_rate
bidder
                           0.0        0.0       1210  0.000000
33across                 136.0       19.0        240  0.079167
appnexus                 175.0       10.0        197  0.050761
criteo                   587.0       21.0        306  0.068627
emx_digital               56.0       20.0        169  0.118343
ix                       184.0       13.0        464  0.028017
medianet                 253.0       20.0        384  0.052083
onemobile                759.0       35.0        407  0.085995
openx                     86.0        7.0        197  0.035533
pubmatic                 255.0       57.0        298  0.191275
pulsepoint                71.0        5.0        134  0.037313
rhythmone                160.0       18.0        246  0.073171
rubicon                   33.0        0.0        178  0.000000
sharethrough             104.0       10.0        139  0.071942
sovrn                     14.0        1.0        102  0.009804
teads                    323.0       16.0         48  0.333333
triplelift               108.0       10.0        232  0.043103
undertone                 52.0       16.0         49  0.326531

### Part 1: Describe how you would build a logistic regression model to predict the probability of a bid winning (win) based on the other columns. 
### What features would you select and why?

BUILDING A LR MODEL

STEP 1: drop all redundant or columns that don't give information about winning or losing like device type, time zone etc.

STEP 2: check for missing values and fill them using forward fill, backward fill, interpolation, etc

STEP 3: check if new features can be calculated from exisiting features and create new features

STEP 4: create a corealation matrix that gives information about the featurs that co-relate with the output here it is win_rate

STEP 5: if there are columns that have very little effect on output variable do not use them.

STEP 6: Check for outlier data points and fix them.

STEP 7: Group data based of column values or seperate them into individual columns. 

STEP 8: create a simple LR model and check for efficiency. perform fine tuning using GridSearch or similar methods

Selecting relevant features from given data
Somme data points are in range and can be simiplified by calculating the avaerage. prebid_win_count and win_count tell us how often a bidder wins a final bid. Accounting for the max_bid and average bid by each bidder also tells the bid range where bids are won for specific ads. A realtion betweeen prebid_winning_bid and sum_winning_bid tells the the gap in the bids when placed pre-auction and on the day of the auction. This will help deterimine what features will give the high probability of winning a bid.

'prebid_win_count',
       'win_count', 'sum_bid', 'sum_time_to_respond', 'median', 'min_bid',
       'max_bid', 'avg_bid', 'sum_2nd_highest_bid', 'sum_prebid_winning_bid',
       'sum_winning_bid',

### Part 2: Based on the following results from a logistic regression model trained on the dataset, interpret the coefficients: 
### bid_amount: Coefficient = 0.8 
### time_to_bid: Coefficient = -0.4 
### ad_unit_A: Coefficient = 0.3 (reference category: ad_unit_B)

Since the bid_amount is closer to 1 this indicates that this feature is strongly co-related with the probabiltiy of winning, i.e high bid amount indicates winning a bid. 

time_to_bid is less than 1 meaning that a the longer a bidder takes time to bid it lowers it probaility of winning. So a bidder should place bids quickly. 

ad_unit_A having a value of 0.3 indicates that it has a less relted with the output and is dependent of another varibale unit_B. Example footer and header of a page and similar items. 
ad_unit_A  is also dependent of the value of ad_unit_B. This means that value of ad_unit_A is dependent on ad_unit_B. So if a bidder bids for unit_A will liekly to bid for unit_B. Bidding for both these would result in a slighly high probability of winning. 
Correction made after: 
bidder bidding for ad_unit_A will like to have a high probability of winning than bidder bidding for ad_unit_B 
Also, the odds that a bidder probabilty is given by e^(coefficient_value). With each increase in unit value the probability of winning increases by e^(coefficient_value)

### CLEANER CODE

In [10]:
df = pd.read_csv('analysis.csv')
df.head()

,Unnamed: 0,date_hour,client,device_type,time_zone,os_name,browser_name,ad_unit,size,bidder,...,sum_time_to_respond,median,min_bid,max_bid,avg_bid,sum_2nd_highest_bid,sum_prebid_winning_bid,sum_winning_bid,sum_nobid,sum_timeout
0,0,2021-04-11T01:00:00,asc126828,Desktop,America/Chicago,Linux,Chrome-85.04183133,div-gpt-ad-BT-D-Footers,728x90,onemobile,...,6614.0,NaN,0.58520,0.58520,0.585200,0.5852,0.5852,NaN,NaN,NaN
1,1,2021-04-11T01:00:00,asc126828,Desktop,America/Chicago,Linux,Chrome-85.04183133,div-gpt-ad-BT-D-Footers,728x90,rhythmone,...,5171.0,NaN,0.33945,0.34875,0.344100,NaN,NaN,NaN,NaN,NaN
2,2,2021-04-11T01:00:00,asc126828,Desktop,America/Chicago,Linux,Chrome-85.04183133,div-gpt-ad-BT-D-InLine-1,300x250,undertone,...,1523.0,NaN,0.96000,0.96000,0.960000,NaN,NaN,NaN,NaN,NaN
3,3,2021-04-11T01:00:00,asc126828,Desktop,America/Chicago,Linux,Chrome-85.04183133,div-gpt-ad-BT-D-O-300x250-1,300x250,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,2021-04-11T01:00:00,asc126828,Desktop,America/Chicago,Linux,Chrome-85.04183133,div-gpt-ad-BT-D-O-300x250-1,300x250,rhythmone,...,3570.0,0.34875,0.34410,0.34875,0.346425,NaN,NaN,NaN,NaN,NaN

In [14]:
bidder_counts = df['bidder'].value_counts().reset_index()
bidder_counts.columns = ['bidder', 'total_bids']
bidder_counts

          bidder  total_bids
0                       1210
1             ix         464
2      onemobile         407
3       medianet         384
4         criteo         306
5       pubmatic         298
6      rhythmone         246
7       33across         240
8     triplelift         232
9       appnexus         197
10         openx         197
11       rubicon         178
12   emx_digital         169
13  sharethrough         139
14    pulsepoint         134
15         sovrn         102
16     undertone          49
17         teads          48

In [17]:
bidder_data = df.groupby('bidder', as_index=False)['win_count'].sum()
bidder_data

          bidder  win_count
0                       0.0
1       33across       19.0
2       appnexus       10.0
3         criteo       21.0
4    emx_digital       20.0
5             ix       13.0
6       medianet       20.0
7      onemobile       35.0
8          openx        7.0
9       pubmatic       57.0
10    pulsepoint        5.0
11     rhythmone       18.0
12       rubicon        0.0
13  sharethrough       10.0
14         sovrn        1.0
15         teads       16.0
16    triplelift       10.0
17     undertone       16.0

In [18]:
win_rate_df = bidder_counts.merge(bidder_data, on='bidder')
win_rate_df

          bidder  total_bids  win_count
0                       1210        0.0
1             ix         464       13.0
2      onemobile         407       35.0
3       medianet         384       20.0
4         criteo         306       21.0
5       pubmatic         298       57.0
6      rhythmone         246       18.0
7       33across         240       19.0
8     triplelift         232       10.0
9       appnexus         197       10.0
10         openx         197        7.0
11       rubicon         178        0.0
12   emx_digital         169       20.0
13  sharethrough         139       10.0
14    pulsepoint         134        5.0
15         sovrn         102        1.0
16     undertone          49       16.0
17         teads          48       16.0

In [21]:
win_rate_df['win_rate'] = win_rate_df['win_count'] / win_rate_df['total_bids']
win_rate_df.sort_values(by='win_rate', ascending=False, inplace=True)
win_rate_df

          bidder  total_bids  win_count  win_rate
17         teads          48       16.0  0.333333
16     undertone          49       16.0  0.326531
5       pubmatic         298       57.0  0.191275
12   emx_digital         169       20.0  0.118343
2      onemobile         407       35.0  0.085995
7       33across         240       19.0  0.079167
6      rhythmone         246       18.0  0.073171
13  sharethrough         139       10.0  0.071942
4         criteo         306       21.0  0.068627
3       medianet         384       20.0  0.052083
9       appnexus         197       10.0  0.050761
8     triplelift         232       10.0  0.043103
14    pulsepoint         134        5.0  0.037313
10         openx         197        7.0  0.035533
1             ix         464       13.0  0.028017
15         sovrn         102        1.0  0.009804
11       rubicon         178        0.0  0.000000
0                       1210        0.0  0.000000

In [29]:
print('Bidder '+ win_rate_df['bidder'].iloc[0] + ' has the highest Win Rate: ' + str(win_rate_df['win_rate'].iloc[0]))

Bidder teads has the highest Win Rate: 0.3333333333333333